- name: Update apt packages
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: yes
    force_apt_get: yes
    update_cache: yes
  when: 
    - ansible_os_family == "Debian"

- name: Update yum packages
  yum:
    name: "*"
    state: latest
  when:
    - ansible_os_family == "RedHat"
